### PR TITLE
Added speaker images, put in speaker info, fixed fonts for speakers

### LINKED ISSUE #26: Add speaker details
Add images and speaker info to `SpeakerData.js`

### PR DESCRIPTION
**Pull request by llennemann**
Closes #26 

Didn't include the labs for some of the speakers because otherwise the text would be too long.

Still to do: in the pop up modal, images are distorted

### CODE REVIEW

File: src/components/data/SpeakerData.js [hunk 1]
```diff
@@ -1,113 +1,93 @@
...
     {
         id: 5,
-        name: "Ana Chkhaidze",
-        day: 3,
-        event: "Career Panel",
-        img: "AnaChkhaidze.jpg",
-        title: "PhD Student at UCSD",
+        name: "Sam Hande",
+        day: 2,
+        event: "TBD",
```
Comment (vchou105) [inline src/components/data/SpeakerData.js:46]: I think we can just replace TBD with Day 2 workshop or something - might sound better than TBD?

File: src/components/pages/Speakers.js [hunk 2]
```diff
@@ -19,9 +19,8 @@ function Events() {
         <div className="container py-5">
             <div className="speakers-title header-gradient pt-5">
                 <h1 className="">Speakers</h1>
```
Comment (vchou105) [inline src/components/pages/Speakers.js:21]: We can prob comment this out or remove?

**Review by vchou105 — APPROVED** [review]

File: src/components/pages/Speakers.js [hunk 3]
```diff
@@ -17,9 +17,7 @@ function Events() {
 
     return (
         <div className="container py-5">
-            <div className="speakers-title header-gradient pt-5">
-                <h1 className="">Speakers</h1>
-            </div>
+            <h1 className="">Speakers</h1>
```
Comment (vchou105) [inline src/components/pages/Speakers.js:20]: I think we can comment out this heading since the nav bar is underlined above too? But if you want to keep it that works too
